In [160]:
import pandas as pd
import numpy as np
import pickle
import re
import nltk
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from sklearn.metrics import accuracy_score,fbeta_score,classification_report
from nltk.tokenize import word_tokenize

from nltk.corpus import stopwords
nltk.download('stopwords')
stop=stopwords.words("english")

from nltk.stem.porter import PorterStemmer
from nltk.stem import SnowballStemmer
ss = SnowballStemmer("english")
ps = PorterStemmer()


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\anktr\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [161]:
df = pd.read_csv("data/spam.csv",encoding='latin-1')
df

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [162]:
df.drop(["Unnamed: 2","Unnamed: 3","Unnamed: 4"],axis=1,inplace=True)

In [163]:
df

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [164]:
df.describe()

v1                      v2
count   5572                    5572
unique     2                    5169
top      ham  Sorry, I'll call later
freq    4825                      30

In [165]:
df['v1'].value_counts()

ham     4825
spam     747
Name: v1, dtype: int64

In [166]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   v1      5572 non-null   object
 1   v2      5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [167]:
import string
def cleanText(message):
    #message = message.translate(str.maketrans('ranjan', 'ranjan', string.punctuation))
    message = re.sub('[^a-zA-Z]', ' ', message)
    message = message.lower()
    message = message.split()
    words = [ss.stem(word) for word in message if word not in stop]
    return " ".join(words)

df["processed_text"] = df["v2"].apply(cleanText)

In [168]:
df

v1                                                 v2  \
0      ham  Go until jurong point, crazy.. Available only ...   
1      ham                      Ok lar... Joking wif u oni...   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...   
3      ham  U dun say so early hor... U c already then say...   
4      ham  Nah I don't think he goes to usf, he lives aro...   
...    ...                                                ...   
5567  spam  This is the 2nd time we have tried 2 contact u...   
5568   ham              Will Ì_ b going to esplanade fr home?   
5569   ham  Pity, * was in mood for that. So...any other s...   
5570   ham  The guy did some bitching but I acted like i'd...   
5571   ham                         Rofl. Its true to its name   

                                         processed_text  
0     go jurong point crazi avail bugi n great world...  
1                                 ok lar joke wif u oni  
2     free entri wkli comp win fa cup final tkts st ...  
3                   u dun say earli hor u c alreadi say  
4                  nah think goe usf live around though  
...                                                 ...  
5567  nd time tri contact u u pound prize claim easi...  
5568                              b go esplanad fr home  
5569                                  piti mood suggest  
5570  guy bitch act like interest buy someth els nex...  
5571                                     rofl true name  

[5572 rows x 3 columns]

In [170]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [171]:
vect = TfidfVectorizer(encoding="latin-1",strip_accents='unicode')

In [172]:
features = vect.fit_transform(df['processed_text'])

In [174]:
features

<5572x6216 sparse matrix of type '<class 'numpy.float64'>'
	with 44832 stored elements in Compressed Sparse Row format>

In [63]:
X = vect.fit_transform(df['processed_text']).toarray

In [200]:
# Transformer Model>...

X_fit = X

In [65]:
df_vector = pd.DataFrame(X,columns=vect.get_feature_names())
df_vector

aa  aah  aaniy  aaooooright  aathi   ab  abbey  abdomen  abeg  abel  \
0     0.0  0.0    0.0          0.0    0.0  0.0    0.0      0.0   0.0   0.0   
1     0.0  0.0    0.0          0.0    0.0  0.0    0.0      0.0   0.0   0.0   
2     0.0  0.0    0.0          0.0    0.0  0.0    0.0      0.0   0.0   0.0   
3     0.0  0.0    0.0          0.0    0.0  0.0    0.0      0.0   0.0   0.0   
4     0.0  0.0    0.0          0.0    0.0  0.0    0.0      0.0   0.0   0.0   
...   ...  ...    ...          ...    ...  ...    ...      ...   ...   ...   
5567  0.0  0.0    0.0          0.0    0.0  0.0    0.0      0.0   0.0   0.0   
5568  0.0  0.0    0.0          0.0    0.0  0.0    0.0      0.0   0.0   0.0   
5569  0.0  0.0    0.0          0.0    0.0  0.0    0.0      0.0   0.0   0.0   
5570  0.0  0.0    0.0          0.0    0.0  0.0    0.0      0.0   0.0   0.0   
5571  0.0  0.0    0.0          0.0    0.0  0.0    0.0      0.0   0.0   0.0   

      ...  zero   zf  zhong  zindgi  zoe  zogtorius  zoom  zouk   zs  zyada  
0     ...   0.0  0.0    0.0     0.0  0.0        0.0   0.0   0.0  0.0    0.0  
1     ...   0.0  0.0    0.0     0.0  0.0        0.0   0.0   0.0  0.0    0.0  
2     ...   0.0  0.0    0.0     0.0  0.0        0.0   0.0   0.0  0.0    0.0  
3     ...   0.0  0.0    0.0     0.0  0.0        0.0   0.0   0.0  0.0    0.0  
4     ...   0.0  0.0    0.0     0.0  0.0        0.0   0.0   0.0  0.0    0.0  
...   ...   ...  ...    ...     ...  ...        ...   ...   ...  ...    ...  
5567  ...   0.0  0.0    0.0     0.0  0.0        0.0   0.0   0.0  0.0    0.0  
5568  ...   0.0  0.0    0.0     0.0  0.0        0.0   0.0   0.0  0.0    0.0  
5569  ...   0.0  0.0    0.0     0.0  0.0        0.0   0.0   0.0  0.0    0.0  
5570  ...   0.0  0.0    0.0     0.0  0.0        0.0   0.0   0.0  0.0    0.0  
5571  ...   0.0  0.0    0.0     0.0  0.0        0.0   0.0   0.0  0.0    0.0  

[5572 rows x 6216 columns]

In [66]:
cv= CountVectorizer()

In [67]:
v = cv.fit_transform(df['processed_text']).toarray()

In [68]:
v

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [69]:
v.shape

(5572, 6216)

In [81]:
df['v1'].map({'ham':0,'spam':1})

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: v1, Length: 5572, dtype: int64

In [84]:
y= df['v1']

In [85]:
# Models: 
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB

In [87]:
xtrain, xtest, ytrain,ytest = train_test_split(df_vector , y,test_size=0.21,random_state=345)

In [94]:
xtrain.shape ,ytrain.shape, ytest.shape, xtest.shape

((4401, 6216), (4401,), (1171,), (1171, 6216))

In [95]:
logit_model = LogisticRegression()
logit_model.fit(xtrain, ytrain)

LogisticRegression()

In [97]:
ypred = logit_model.predict(xtest)

In [114]:
logit_score=accuracy_score(ytest , ypred)

In [99]:
gaussian_model = GaussianNB()
gaussian_model.fit(xtrain, ytrain)

GaussianNB()

In [103]:
ypred = gaussian_model.predict(xtest)

In [108]:
gaussian_score=accuracy_score(ytest , ypred)

In [109]:
multinomial_model = MultinomialNB()
multinomial_model.fit(xtrain, ytrain)

MultinomialNB()

In [110]:
ypred= multinomial_model.predict(xtest)

In [111]:
multi_score=accuracy_score(ytest , ypred)

In [195]:
print("Accuracy of different Models:")
print("LogisticRegression: {0}\nGaussian Model: {1}".format(logit_score,gaussian_score))

Accuracy of different Models:
LogisticRegression: 0.9701110162254484
Gaussian Model: 0.9701110162254484


In [196]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [208]:
text = "Joe"
text = list(text)

In [209]:
X_cv = CountVectorizer()

In [210]:
vect

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [214]:
vect = vect.transform(text).toarray()

AttributeError: 'numpy.ndarray' object has no attribute 'transform'